

runtime: python37
entrypoint: gunicorn -b :$PORT app:app
service: "foosball"

env_variables:

    SQL_USER: root
    SQL_PASSWORD: will123
    SQL_DATABASE: foos
    INSTANCE_CONNECTION_NAME: misc-apps:us-central1-a:foos


beta_settings:
    cloud_sql_instances: "misc-apps:us-central1-a:foos"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cpu_utilization:
    target_utilization: 0.5
