

runtime: python37
entrypoint: gunicorn -b :$PORT app:app
service: "foosball"

env_variables:

    SQL_USER: root
    SQL_PASSWORD: will123
    SQL_DATABASE: foos
    INSTANCE_CONNECTION_NAME: cpb100-213205:us-central1:misc-apps


beta_settings:
    cloud_sql_instances: "cpb100-213205:us-central1:misc-apps"
