# use cloud sql and datstore combination.

runtime: python37
entrypoint: gunicorn -b :$PORT main:app
service: "foosball"
env: standard

env_variables:

    SQL_USER: root
    SQL_PASSWORD: password
    SQL_DATABASE: foos
    INSTANCE_CONNECTION_NAME: cpb100-213205:us-central1:misc-apps


beta_settings:
    cloud_sql_instances: "cpb100-213205:us-central1:misc-apps"
